console.log("abdul")
var a = prompt(" enter any number")
var b =1
if (a==2) {
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
}
if(a==3){
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

}   
if(a==4){
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    
}   
if(a==5){
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    
}
if(a==6){
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    
}if(a==7){
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    
}if(a==8){
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    
}if(a==9){
    document.write(`${a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
      document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
      
    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    document.write(`${++a}*1 =`, a*1 +"<br>")
    document.write(`${a}*2 =`, a*2 +"<br>")
    document.write(`${a}*3 =`, a*3 +"<br>")
    document.write(`${a}*4 =`, a*4 +"<br>")
    document.write(`${a}*5 =`, a*5 +"<br>")
    document.write(`${a}*6 =`, a*6 +"<br>")
    document.write(`${a}*7 =`, a*7 +"<br>")
    document.write(`${a}*8 =`, a*8 +"<br>")
    document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

    
}if(a==10){
  document.write(`${a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
    
  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  
}if(a==11){
  document.write(`${a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
    document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")
    
  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  document.write(`${++a}*1 =`, a*1 +"<br>")
  document.write(`${a}*2 =`, a*2 +"<br>")
  document.write(`${a}*3 =`, a*3 +"<br>")
  document.write(`${a}*4 =`, a*4 +"<br>")
  document.write(`${a}*5 =`, a*5 +"<br>")
  document.write(`${a}*6 =`, a*6 +"<br>")
  document.write(`${a}*7 =`, a*7 +"<br>")
  document.write(`${a}*8 =`, a*8 +"<br>")
  document.write(`${a}*9 =`, a*9 +"<br>")
  document.write(`${a}*10 =`, a*10 +"<br>"+"<hr>")

  
}





